---
galaxy_info:
  author: NVIDIA Corporation
  description: Audit and report on BCM cluster configuration
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - nvidia
    - bcm
    - audit
    - reporting

dependencies: []
