---
galaxy_info:
  author: NVIDIA Corporation
  description: Deploy BCM Agent on RHEL systems using Podman Quadlet
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - nvidia
    - bcm
    - monitoring
    - quadlet
    - podman

dependencies: []
