---
galaxy_info:
  author: NVIDIA Corporation
  description: Deploy RHEL+Slurm clusters on BCM via PXE
  company: NVIDIA
  license: GPL-3.0-or-later
  min_ansible_version: '2.15'
  platforms:
    - name: EL
      versions:
        - '9'
  galaxy_tags:
    - nvidia
    - bcm
    - rhel
    - slurm
    - hpc
    - pxe

dependencies: []
